---
resources:
- name: concourse-examples
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/examples

jobs:
# update this pipeline before updating child pipelines
- name: set-self
  public: true
  plan:
  - get: concourse-examples
    trigger: true
  - set_pipeline: set-pipelines
    file: concourse-examples/pipelines/set-pipelines.yml
- name: set-example-pipelines
  public: true
  plan:
  - get: concourse-examples
    trigger: true
    passed: [set-self]
  - set_pipeline: job
    file: concourse-examples/pipelines/hello-world.yml
  - set_pipeline: separate-task-config
    file: concourse-examples/pipelines/separate-task-config.yml
  - set_pipeline: serial-job
    file: concourse-examples/pipelines/serial-job.yml
  - set_pipeline: hooks
    file: concourse-examples/pipelines/job-and-task-hooks.yml
  - set_pipeline: golang-lib
    file: concourse-examples/pipelines/golang-lib.yml
  - set_pipeline: rails
    file: concourse-examples/pipelines/rails-app-testing.yml
  - set_pipeline: nodejs
    file: concourse-examples/pipelines/nodejs-app-testing.yml
  - set_pipeline: php
    file: concourse-examples/pipelines/php-larvel-app-testing.yml
  - set_pipeline: java
    file: concourse-examples/pipelines/java.yml
